# Site settings
title: "YG1ee Weblog"
email: fanfolderkim@gmail.com
description: "A dark blog theme for Jekyll."
baseurl: ""
url: "https://yg1ee.github.io"
site: "https://yg1ee.github.io"
title_description: "개발 일지"
title_image: "./res/tux.svg"
google_analytics: "G-5LHFKCB0XQ"
github_repository: https://github.com/YG1ee
post_limit: 5

# Social usernames/URLs
twitter_username: YG1ee
github_username:  YG1ee
#instagram_username: 
#reddit_username: 
#linkedin_link: 
#google_plus_link: 
#stackoverflow_link: 
# xing_link:
# facebook_link:

timezone: Asia/Seoul

# Footer
footer_left: "Theme made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_jacobtomlinson\">Jacob Tomlinson</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
